#!/usr/bin/env bash

PATCHED_FONTS=./patched
INSTALL_DIR=~/.local/share/fonts/MonoLisa

for font_dir in $PATCHED_FONTS/*; do
	patched_dir="${font_dir##*/}"
	echo ">>> $patched_dir"

	if [[ -d "${INSTALL_DIR}/${patched_dir}" ]]; then
		echo "deleting existing version"
		rm -rf $INSTALL_DIR/$patched_dir
	fi

	dest=$INSTALL_DIR/$patched_dir
	mkdir $dest && cp -v $font_dir/* $dest
done

echo "Don't forget to run 'fc-cache -f -v'"
